name: Build, test and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: "9.0.x"
      ASPNETCORE_URLS: "http://localhost:5276"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build

      - name: Install Playwright CLI and Browsers
        run: |
          # Install CLI globally
          dotnet tool install --global Microsoft.Playwright.CLI
          # Add the .NET tools folder to the PATH for the Playwright command
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          # Install browsers
          playwright install --with-deps

      - name: Start app
        run: |
          dotnet run --project StarWarsApp/StarWarsApp.csproj --configuration Release --urls $ASPNETCORE_URLS &

          echo "Waiting for app to start..."
          # Wait loop as before
          for i in {1..30}; do
            if curl -sSf "$ASPNETCORE_URLS" > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Still waiting..."
            sleep 2
          done

      - name: Run E2E tests
        run: dotnet test StarWarsApp.E2E/StarWarsApp.E2E.csproj --configuration Release

      - name: Publish app
        run: dotnet publish StarWarsApp/StarWarsApp.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "starwars"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
